<?php

namespace Database\Seeders;

use App\Models\Blog;
use Illuminate\Database\Seeder;

class BlogSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $blogs = [
            [
                "slug" => "tendances-design-2025",
                "title_fr" => 'Les Tendances Design d\'Intérieur 2025',
                "title_en" => "Interior Design Trends 2025",
                "title_es" => "Tendencias de Diseño de Interiores 2025",
                "title_it" => 'Tendenze del Design d\'Interni 2025',
                "content_fr" =>
                    "L'année 2025 marque un tournant dans l'univers du design d'intérieur, avec l'émergence de tendances qui réinventent notre rapport à l'espace et aux matériaux.\n\n**Le Retour aux Matériaux Naturels**\n\nLe bois brut, la pierre naturelle et les fibres végétales s'imposent comme des incontournables. Ces matériaux apportent authenticité et chaleur à nos intérieurs, créant une connexion tangible avec la nature. Le travertin fait un retour remarqué, tout comme le chêne vieilli et le lin naturel.\n\n**Les Couleurs Audacieuses**\n\nFini la tyrannie du blanc total. 2025 célèbre les couleurs riches et saturées : terracotta profond, vert forêt, bleu nuit et ocre doré. Ces teintes créent des ambiances enveloppantes et sophistiquées, parfaites pour des intérieurs de caractère.\n\n**Le Design Biophilique**\n\nL'intégration de la nature dans nos espaces de vie devient primordiale. Murs végétaux, grandes baies vitrées et matériaux organiques créent des environnements qui favorisent le bien-être et la sérénité. Cette approche va au-delà de la simple décoration pour devenir une philosophie de vie.\n\n**La Technologie Invisible**\n\nLa domotique se fait discrète, s'intégrant harmonieusement dans le design sans jamais le dominer. Éclairages intelligents, systèmes audio invisibles et commandes tactiles se fondent dans l'architecture pour créer des espaces à la fois high-tech et intemporels.\n\n**L'Artisanat Contemporain**\n\nLe fait-main et les pièces uniques retrouvent leurs lettres de noblesse. Céramiques artisanales, mobilier sur mesure et textiles tissés à la main apportent âme et caractère à nos intérieurs, en rupture avec la standardisation.",
                "content_en" =>
                    "The year 2025 marks a turning point in the world of interior design, with emerging trends that reinvent our relationship with space and materials.\n\n**The Return to Natural Materials**\n\nRaw wood, natural stone and plant fibers establish themselves as essentials. These materials bring authenticity and warmth to our interiors, creating a tangible connection with nature. Travertine makes a remarkable comeback, as do aged oak and natural linen.\n\n**Bold Colors**\n\nGone is the tyranny of total white. 2025 celebrates rich and saturated colors: deep terracotta, forest green, midnight blue and golden ochre. These hues create enveloping and sophisticated atmospheres, perfect for characterful interiors.\n\n**Biophilic Design**\n\nIntegrating nature into our living spaces becomes paramount. Living walls, large bay windows and organic materials create environments that promote well-being and serenity. This approach goes beyond simple decoration to become a life philosophy.\n\n**Invisible Technology**\n\nHome automation becomes discreet, integrating harmoniously into design without ever dominating it. Smart lighting, invisible audio systems and touch controls blend into the architecture to create spaces that are both high-tech and timeless.\n\n**Contemporary Craftsmanship**\n\nHandmade and unique pieces regain their prestige. Artisanal ceramics, custom furniture and hand-woven textiles bring soul and character to our interiors, breaking with standardization.",
                "content_es" =>
                    "El año 2025 marca un punto de inflexión en el mundo del diseño de interiores, con tendencias emergentes que reinventan nuestra relación con el espacio y los materiales.\n\n**El Retorno a los Materiales Naturales**\n\nLa madera cruda, la piedra natural y las fibras vegetales se establecen como elementos esenciales. Estos materiales aportan autenticidad y calidez a nuestros interiores, creando una conexión tangible con la naturaleza. El travertino hace un regreso notable, al igual que el roble envejecido y el lino natural.\n\n**Colores Audaces**\n\nSe acabó la tiranía del blanco total. 2025 celebra colores ricos y saturados: terracota profundo, verde bosque, azul medianoche y ocre dorado. Estos tonos crean atmósferas envolventes y sofisticadas, perfectas para interiores con carácter.\n\n**Diseño Biofílico**\n\nIntegrar la naturaleza en nuestros espacios vitales se vuelve primordial. Muros vegetales, grandes ventanales y materiales orgánicos crean ambientes que promueven el bienestar y la serenidad. Este enfoque va más allá de la simple decoración para convertirse en una filosofía de vida.\n\n**Tecnología Invisible**\n\nLa domótica se vuelve discreta, integrándose armoniosamente en el diseño sin dominarlo nunca. Iluminación inteligente, sistemas de audio invisibles y controles táctiles se mezclan con la arquitectura para crear espacios que son a la vez high-tech y atemporales.\n\n**Artesanía Contemporánea**\n\nLo hecho a mano y las piezas únicas recuperan su prestigio. Cerámicas artesanales, muebles a medida y textiles tejidos a mano aportan alma y carácter a nuestros interiores, rompiendo con la estandarización.",
                "content_it" =>
                    'L\'anno 2025 segna una svolta nel mondo del design d\'interni, con tendenze emergenti che reinventano il nostro rapporto con lo spazio e i materiali.\n\n**Il Ritorno ai Materiali Naturali**\n\nLegno grezzo, pietra naturale e fibre vegetali si affermano come elementi essenziali. Questi materiali portano autenticità e calore nei nostri interni, creando una connessione tangibile con la natura. Il travertino fa un ritorno notevole, così come la quercia invecchiata e il lino naturale.\n\n**Colori Audaci**\n\nFinita la tirannia del bianco totale. Il 2025 celebra colori ricchi e saturi: terracotta profondo, verde foresta, blu notte e ocra dorato. Queste tonalità creano atmosfere avvolgenti e sofisticate, perfette per interni di carattere.\n\n**Design Biofilico**\n\nIntegrare la natura nei nostri spazi abitativi diventa fondamentale. Pareti vegetali, grandi vetrate e materiali organici creano ambienti che favoriscono il benessere e la serenità. Questo approccio va oltre la semplice decorazione per diventare una filosofia di vita.\n\n**Tecnologia Invisibile**\n\nLa domotica diventa discreta, integrandosi armoniosamente nel design senza mai dominarlo. Illuminazione intelligente, sistemi audio invisibili e comandi touch si fondono nell\'architettura per creare spazi sia high-tech che senza tempo.\n\n**Artigianato Contemporaneo**\n\nIl fatto a mano e i pezzi unici riacquistano il loro prestigio. Ceramiche artigianali, mobili su misura e tessuti tessuti a mano portano anima e carattere ai nostri interni, rompendo con la standardizzazione.',
                "image" => "medias/images/projects/project-1.jpg",
                "is_published" => true,
                "published_at" => now()->subDays(5),
            ],
            [
                "slug" => "minimalisme-luxe",
                "title_fr" => "Le Minimalisme de Luxe",
                "title_en" => "Luxury Minimalism",
                "title_es" => "Minimalismo de Lujo",
                "title_it" => "Minimalismo di Lusso",
                "content_fr" =>
                    "Le minimalisme de luxe représente l'art subtil de créer des espaces épurés sans sacrifier le confort ni l'élégance. Cette approche exige une maîtrise parfaite de l'équilibre entre simplicité et sophistication.\n\n**La Philosophie du \"Moins c'est Plus\"**\n\nContrairement aux idées reçues, le minimalisme n'est pas synonyme d'austérité. Il s'agit plutôt d'une démarche consciente visant à ne conserver que l'essentiel, mais en choisissant le meilleur. Chaque élément présent dans l'espace doit avoir une raison d'être, qu'elle soit fonctionnelle ou esthétique.\n\n**Les Matériaux Nobles**\n\nDans un intérieur minimaliste de luxe, les matériaux jouent un rôle primordial. Le marbre de Carrare, le bois de noyer massif, le cuir pleine fleur et le lin lavé apportent une richesse tactile et visuelle incomparable. La qualité prime sur la quantité, créant une atmosphère raffinée et intemporelle.\n\n**L'Importance de la Lumière**\n\nLa lumière naturelle devient l'élément central du design. Grandes baies vitrées, puits de lumière et miroirs stratégiquement placés amplifient la luminosité naturelle. L'éclairage artificiel est pensé pour être discret mais efficace, avec des systèmes intégrés qui sculptent l'espace sans l'encombrer.\n\n**Le Détail qui Fait la Différence**\n\nDans un espace minimaliste, chaque détail compte. Les poignées de porte en laiton brossé, les robinetteries design, les interrupteurs affleurants : tout est pensé pour créer une cohérence visuelle parfaite. Les finitions sont impeccables, car rien ne peut se cacher derrière la profusion.\n\n**L'Art de la Mise en Scène**\n\nQuelques pièces d'art soigneusement sélectionnées deviennent les points focaux de l'espace. Une sculpture contemporaine, un tableau abstrait ou une installation lumineuse apportent personnalité et caractère sans rompre l'harmonie générale. Le minimalisme de luxe permet à ces pièces de briller pleinement.",
                "content_en" =>
                    'Luxury minimalism represents the subtle art of creating refined spaces without sacrificing comfort or elegance. This approach requires perfect mastery of the balance between simplicity and sophistication.\n\n**The Philosophy of "Less is More"**\n\nContrary to popular belief, minimalism is not synonymous with austerity. It is rather a conscious approach aimed at keeping only the essential, but choosing the best. Every element present in the space must have a reason to be, whether functional or aesthetic.\n\n**Noble Materials**\n\nIn a luxury minimalist interior, materials play a primordial role. Carrara marble, solid walnut wood, full-grain leather and washed linen bring incomparable tactile and visual richness. Quality takes precedence over quantity, creating a refined and timeless atmosphere.\n\n**The Importance of Light**\n\nNatural light becomes the central element of design. Large bay windows, skylights and strategically placed mirrors amplify natural brightness. Artificial lighting is designed to be discreet but effective, with integrated systems that sculpt the space without cluttering it.\n\n**The Detail that Makes the Difference**\n\nIn a minimalist space, every detail counts. Brushed brass door handles, designer faucets, flush switches: everything is designed to create perfect visual coherence. Finishes are impeccable, because nothing can hide behind profusion.\n\n**The Art of Staging**\n\nA few carefully selected pieces of art become the focal points of the space. A contemporary sculpture, an abstract painting or a light installation bring personality and character without breaking the general harmony. Luxury minimalism allows these pieces to shine fully.',
                "content_es" =>
                    'El minimalismo de lujo representa el arte sutil de crear espacios refinados sin sacrificar el confort ni la elegancia. Este enfoque requiere un dominio perfecto del equilibrio entre simplicidad y sofisticación.\n\n**La Filosofía del "Menos es Más"**\n\nContrariamente a la creencia popular, el minimalismo no es sinónimo de austeridad. Es más bien un enfoque consciente destinado a conservar solo lo esencial, pero eligiendo lo mejor. Cada elemento presente en el espacio debe tener una razón de ser, ya sea funcional o estética.\n\n**Materiales Nobles**\n\nEn un interior minimalista de lujo, los materiales juegan un papel primordial. Mármol de Carrara, madera de nogal macizo, cuero de grano completo y lino lavado aportan una riqueza táctil y visual incomparable. La calidad tiene prioridad sobre la cantidad, creando una atmósfera refinada y atemporal.\n\n**La Importancia de la Luz**\n\nLa luz natural se convierte en el elemento central del diseño. Grandes ventanales, tragaluces y espejos estratégicamente ubicados amplifican el brillo natural. La iluminación artificial está diseñada para ser discreta pero efectiva, con sistemas integrados que esculpen el espacio sin saturarlo.\n\n**El Detalle que Marca la Diferencia**\n\nEn un espacio minimalista, cada detalle cuenta. Manijas de puerta de latón cepillado, grifería de diseño, interruptores empotrados: todo está diseñado para crear una coherencia visual perfecta. Los acabados son impecables, porque nada puede esconderse detrás de la profusión.\n\n**El Arte de la Puesta en Escena**\n\nAlgunas piezas de arte cuidadosamente seleccionadas se convierten en los puntos focales del espacio. Una escultura contemporánea, una pintura abstracta o una instalación de luz aportan personalidad y carácter sin romper la armonía general. El minimalismo de lujo permite que estas piezas brillen plenamente.',
                "content_it" =>
                    'Il minimalismo di lusso rappresenta l\'arte sottile di creare spazi raffinati senza sacrificare il comfort o l\'eleganza. Questo approccio richiede una perfetta padronanza dell\'equilibrio tra semplicità e sofisticazione.\n\n**La Filosofia del "Meno è Più"**\n\nContrariamente alla credenza popolare, il minimalismo non è sinonimo di austerità. È piuttosto un approccio consapevole volto a mantenere solo l\'essenziale, ma scegliendo il meglio. Ogni elemento presente nello spazio deve avere una ragione d\'essere, sia funzionale che estetica.\n\n**Materiali Nobili**\n\nIn un interno minimalista di lusso, i materiali giocano un ruolo primordiale. Marmo di Carrara, legno di noce massello, pelle pieno fiore e lino lavato portano una ricchezza tattile e visiva incomparabile. La qualità ha la precedenza sulla quantità, creando un\'atmosfera raffinata e senza tempo.\n\n**L\'Importanza della Luce**\n\nLa luce naturale diventa l\'elemento centrale del design. Grandi vetrate, lucernari e specchi posizionati strategicamente amplificano la luminosità naturale. L\'illuminazione artificiale è progettata per essere discreta ma efficace, con sistemi integrati che scolpiscono lo spazio senza ingombrarlo.\n\n**Il Dettaglio che Fa la Differenza**\n\nIn uno spazio minimalista, ogni dettaglio conta. Maniglie delle porte in ottone spazzolato, rubinetteria di design, interruttori a filo: tutto è progettato per creare una perfetta coerenza visiva. Le finiture sono impeccabili, perché nulla può nascondersi dietro la profusione.\n\n**L\'Arte della Messa in Scena**\n\nAlcune opere d\'arte accuratamente selezionate diventano i punti focali dello spazio. Una scultura contemporanea, un dipinto astratto o un\'installazione luminosa portano personalità e carattere senza rompere l\'armonia generale. Il minimalismo di lusso permette a questi pezzi di brillare pienamente.',
                "image" => "medias/images/projects/project-2.jpg",
                "is_published" => true,
                "published_at" => now()->subDays(12),
            ],
            [
                "slug" => "couleurs-automne",
                "title_fr" => 'Palette de Couleurs d\'Automne',
                "title_en" => "Autumn Color Palette",
                "title_es" => "Paleta de Colores de Otoño",
                "title_it" => "Tavolozza di Colori Autunnali",
                "content_fr" =>
                    "Les couleurs automnales transforment nos intérieurs en havres de chaleur et de confort. Cette saison inspire une palette riche et enveloppante qui apporte caractère et profondeur à chaque espace.\n\n**Les Ocres et Terracotta**\n\nCes teintes chaudes évoquent la terre cuite méditerranéenne et les paysages toscans. Du beige rosé au rouge brique profond, elles créent une atmosphère accueillante et sophistiquée. Parfaites pour un pan de mur statement ou des textiles d'ameublement, elles apportent instantanément une sensation de cocooning.\n\n**Les Verts Profonds**\n\nDu vert olive au vert forêt, ces nuances rappellent la nature en transition automnale. Associés à des tons neutres ou des cuivres, ils créent des ambiances à la fois apaisantes et élégantes. Idéaux pour des espaces comme la bibliothèque ou le salon, ils invitent à la contemplation.\n\n**Les Bruns Chaleureux**\n\nChocolat, cognac, caramel : ces tons gourmands apportent richesse et profondeur. Particulièrement efficaces en touches via le mobilier et les accessoires, ils se marient parfaitement avec des matériaux naturels comme le bois et le cuir.\n\n**L'Association des Textures**\n\nPour sublimer ces couleurs automnales, le choix des textures est crucial. Velours côtelé, laine bouclée, lin épais et cuir vieilli amplifient la sensation de chaleur. Les finitions mates absorbent la lumière et créent des atmosphères intimistes.\n\n**L'Éclairage Complémentaire**\n\nUn éclairage doré et tamisé sublime ces teintes chaudes. Lampes à abat-jour en lin, bougies et guirlandes lumineuses créent une ambiance chaleureuse qui prolonge les soirées d'automne dans le confort de son intérieur.",
                "content_en" =>
                    "Autumn colors transform our interiors into havens of warmth and comfort. This season inspires a rich and enveloping palette that brings character and depth to every space.\n\n**Ochres and Terracotta**\n\nThese warm hues evoke Mediterranean terracotta and Tuscan landscapes. From rosy beige to deep brick red, they create a welcoming and sophisticated atmosphere. Perfect for a statement wall or upholstery textiles, they instantly bring a cocooning sensation.\n\n**Deep Greens**\n\nFrom olive green to forest green, these shades recall nature in autumn transition. Associated with neutral tones or coppers, they create atmospheres that are both soothing and elegant. Ideal for spaces like the library or living room, they invite contemplation.\n\n**Warm Browns**\n\nChocolate, cognac, caramel: these gourmet tones bring richness and depth. Particularly effective in touches via furniture and accessories, they pair perfectly with natural materials like wood and leather.\n\n**The Association of Textures**\n\nTo enhance these autumn colors, the choice of textures is crucial. Ribbed velvet, curly wool, thick linen and aged leather amplify the feeling of warmth. Matte finishes absorb light and create intimate atmospheres.\n\n**Complementary Lighting**\n\nGolden and subdued lighting enhances these warm hues. Linen-shaded lamps, candles and fairy lights create a warm ambiance that extends autumn evenings in the comfort of your interior.",
                "content_es" =>
                    "Los colores otoñales transforman nuestros interiores en refugios de calidez y confort. Esta estación inspira una paleta rica y envolvente que aporta carácter y profundidad a cada espacio.\n\n**Ocres y Terracota**\n\nEstos tonos cálidos evocan la terracota mediterránea y los paisajes toscanos. Desde beige rosado hasta rojo ladrillo profundo, crean una atmósfera acogedora y sofisticada. Perfectos para una pared destacada o textiles de tapicería, aportan instantáneamente una sensación de acogida.\n\n**Verdes Profundos**\n\nDesde verde oliva hasta verde bosque, estos tonos recuerdan la naturaleza en transición otoñal. Asociados con tonos neutros o cobres, crean atmósferas tanto relajantes como elegantes. Ideales para espacios como la biblioteca o la sala de estar, invitan a la contemplación.\n\n**Marrones Cálidos**\n\nChocolate, coñac, caramelo: estos tonos gourmet aportan riqueza y profundidad. Particularmente efectivos en toques a través de muebles y accesorios, se combinan perfectamente con materiales naturales como madera y cuero.\n\n**La Asociación de Texturas**\n\nPara realzar estos colores otoñales, la elección de texturas es crucial. Terciopelo acanalado, lana rizada, lino grueso y cuero envejecido amplifican la sensación de calidez. Los acabados mate absorben la luz y crean atmósferas íntimas.\n\n**Iluminación Complementaria**\n\nUna iluminación dorada y tenue realza estos tonos cálidos. Lámparas con pantallas de lino, velas y luces de hadas crean un ambiente cálido que prolonga las tardes de otoño en la comodidad de su interior.",
                "content_it" =>
                    'I colori autunnali trasformano i nostri interni in rifugi di calore e comfort. Questa stagione ispira una tavolozza ricca e avvolgente che porta carattere e profondità a ogni spazio.\n\n**Ocra e Terracotta**\n\nQueste tonalità calde evocano la terracotta mediterranea e i paesaggi toscani. Dal beige rosato al rosso mattone profondo, creano un\'atmosfera accogliente e sofisticata. Perfetti per una parete statement o tessuti d\'arredo, portano istantaneamente una sensazione di coccola.\n\n**Verdi Profondi**\n\nDal verde oliva al verde foresta, queste sfumature ricordano la natura in transizione autunnale. Associati a toni neutri o rami, creano atmosfere sia rilassanti che eleganti. Ideali per spazi come la biblioteca o il soggiorno, invitano alla contemplazione.\n\n**Marroni Caldi**\n\nCioccolato, cognac, caramello: questi toni gourmet portano ricchezza e profondità. Particolarmente efficaci in tocchi tramite mobili e accessori, si abbinano perfettamente con materiali naturali come legno e pelle.\n\n**L\'Associazione delle Texture**\n\nPer esaltare questi colori autunnali, la scelta delle texture è cruciale. Velluto a coste, lana riccia, lino spesso e pelle invecchiata amplificano la sensazione di calore. Le finiture opache assorbono la luce e creano atmosfere intime.\n\n**Illuminazione Complementare**\n\nUn\'illuminazione dorata e soffusa esalta questi toni caldi. Lampade con paralumi in lino, candele e luci fatate creano un\'atmosfera calda che prolunga le serate autunnali nel comfort del proprio interno.',
                "image" => "medias/images/projects/project-3.jpg",
                "is_published" => true,
                "published_at" => now()->subDays(20),
            ],
            [
                "slug" => "materiaux-durables",
                "title_fr" => "Matériaux Durables et Éco-responsables",
                "title_en" => "Sustainable and Eco-responsible Materials",
                "title_es" => "Materiales Sostenibles y Eco-responsables",
                "title_it" => "Materiali Sostenibili ed Eco-responsabili",
                "content_fr" =>
                    "L'architecture d'intérieur éco-responsable n'est plus une option mais une nécessité. Créer des espaces beaux et durables devient possible grâce à des matériaux innovants qui respectent l'environnement.\n\n**Le Bois Certifié et Recyclé**\n\nPrivilégier le bois issu de forêts gérées durablement (certifications FSC ou PEFC) garantit une exploitation responsable. Le bois de récupération, provenant de granges anciennes ou de chantiers de démolition, apporte un cachet unique tout en évitant le gaspillage. Ces essences patinées par le temps racontent une histoire et créent des ambiances authentiques.\n\n**Les Matériaux Biosourcés**\n\nLe liège, le bambou, la paille et le chanvre offrent d'excellentes alternatives écologiques. Le liège, notamment, possède des propriétés isolantes exceptionnelles et peut être utilisé en revêtement mural ou de sol. Le bambou, à croissance rapide, constitue une option durable pour le mobilier et les accessoires.\n\n**Les Textiles Naturels et Biologiques**\n\nLin, chanvre, coton biologique et laine non traitée créent des intérieurs sains et respectueux de l'environnement. Ces fibres naturelles, cultivées sans pesticides, offrent une qualité supérieure et vieillissent avec élégance. Leur aspect légèrement irrégulier apporte du caractère et de l'authenticité.\n\n**Les Peintures Écologiques**\n\nLes peintures à base d'argile, de chaux ou de caséine remplacent avantageusement les peintures traditionnelles. Sans COV (composés organiques volatils), elles assurent une meilleure qualité de l'air intérieur tout en offrant des finitions mates et profondes incomparables.\n\n**L'Économie Circulaire dans le Design**\n\nChiner des pièces vintage, restaurer du mobilier ancien ou faire appel à des artisans locaux contribue à une démarche éco-responsable. Cette approche permet de créer des intérieurs uniques tout en réduisant l'empreinte carbone.",
                "content_en" =>
                    "Eco-responsible interior architecture is no longer an option but a necessity. Creating beautiful and sustainable spaces becomes possible thanks to innovative materials that respect the environment.\n\n**Certified and Recycled Wood**\n\nFavoring wood from sustainably managed forests (FSC or PEFC certifications) guarantees responsible exploitation. Reclaimed wood, from old barns or demolition sites, brings unique character while avoiding waste. These time-patinated species tell a story and create authentic atmospheres.\n\n**Bio-sourced Materials**\n\nCork, bamboo, straw and hemp offer excellent ecological alternatives. Cork, in particular, has exceptional insulating properties and can be used as wall or floor covering. Bamboo, with rapid growth, constitutes a sustainable option for furniture and accessories.\n\n**Natural and Organic Textiles**\n\nLinen, hemp, organic cotton and untreated wool create healthy and environmentally friendly interiors. These natural fibers, grown without pesticides, offer superior quality and age with elegance. Their slightly irregular appearance brings character and authenticity.\n\n**Ecological Paints**\n\nPaints based on clay, lime or casein advantageously replace traditional paints. Without VOCs (volatile organic compounds), they ensure better indoor air quality while offering incomparable matte and deep finishes.\n\n**Circular Economy in Design**\n\nHunting for vintage pieces, restoring old furniture or calling on local artisans contributes to an eco-responsible approach. This approach allows creating unique interiors while reducing carbon footprint.",
                "content_es" =>
                    "La arquitectura de interiores eco-responsable ya no es una opción sino una necesidad. Crear espacios hermosos y sostenibles se hace posible gracias a materiales innovadores que respetan el medio ambiente.\n\n**Madera Certificada y Reciclada**\n\nFavorecer la madera de bosques gestionados de manera sostenible (certificaciones FSC o PEFC) garantiza una explotación responsable. La madera recuperada, de graneros antiguos o sitios de demolición, aporta un carácter único evitando el desperdicio. Estas especies patinadas por el tiempo cuentan una historia y crean atmósferas auténticas.\n\n**Materiales de Base Biológica**\n\nCorcho, bambú, paja y cáñamo ofrecen excelentes alternativas ecológicas. El corcho, en particular, tiene propiedades aislantes excepcionales y puede usarse como revestimiento de pared o piso. El bambú, de crecimiento rápido, constituye una opción sostenible para muebles y accesorios.\n\n**Textiles Naturales y Orgánicos**\n\nLino, cáñamo, algodón orgánico y lana sin tratar crean interiores saludables y respetuosos con el medio ambiente. Estas fibras naturales, cultivadas sin pesticidas, ofrecen calidad superior y envejecen con elegancia. Su aspecto ligeramente irregular aporta carácter y autenticidad.\n\n**Pinturas Ecológicas**\n\nLas pinturas a base de arcilla, cal o caseína reemplazan ventajosamente las pinturas tradicionales. Sin COV (compuestos orgánicos volátiles), aseguran mejor calidad del aire interior ofreciendo acabados mate y profundos incomparables.\n\n**Economía Circular en el Diseño**\n\nBuscar piezas vintage, restaurar muebles antiguos o recurrir a artesanos locales contribuye a un enfoque eco-responsable. Este enfoque permite crear interiores únicos reduciendo la huella de carbono.",
                "content_it" =>
                    'L\'architettura d\'interni eco-responsabile non è più un\'opzione ma una necessità. Creare spazi belli e sostenibili diventa possibile grazie a materiali innovativi che rispettano l\'ambiente.\n\n**Legno Certificato e Riciclato**\n\nPrivilegiare il legno proveniente da foreste gestite in modo sostenibile (certificazioni FSC o PEFC) garantisce uno sfruttamento responsabile. Il legno di recupero, proveniente da vecchi fienili o cantieri di demolizione, porta un carattere unico evitando lo spreco. Queste essenze patinate dal tempo raccontano una storia e creano atmosfere autentiche.\n\n**Materiali di Origine Biologica**\n\nSughero, bambù, paglia e canapa offrono eccellenti alternative ecologiche. Il sughero, in particolare, ha proprietà isolanti eccezionali e può essere utilizzato come rivestimento murale o pavimentazione. Il bambù, a crescita rapida, costituisce un\'opzione sostenibile per mobili e accessori.\n\n**Tessuti Naturali e Biologici**\n\nLino, canapa, cotone biologico e lana non trattata creano interni sani e rispettosi dell\'ambiente. Queste fibre naturali, coltivate senza pesticidi, offrono qualità superiore e invecchiano con eleganza. Il loro aspetto leggermente irregolare porta carattere e autenticità.\n\n**Vernici Ecologiche**\n\nLe vernici a base di argilla, calce o caseina sostituiscono vantaggiosamente le vernici tradizionali. Senza COV (composti organici volatili), assicurano una migliore qualità dell\'aria interna offrendo finiture opache e profonde incomparabili.\n\n**Economia Circolare nel Design**\n\nCaccia a pezzi vintage, restauro di mobili antichi o ricorso ad artigiani locali contribuisce a un approccio eco-responsabile. Questo approccio permette di creare interni unici riducendo l\'impronta di carbonio.',
                "image" => "medias/images/projects/project-4.jpg",
                "is_published" => true,
                "published_at" => now()->subDays(30),
            ],
            [
                "slug" => "art-contemporain-interieur",
                "title_fr" => 'Intégrer l\'Art Contemporain',
                "title_en" => "Integrating Contemporary Art",
                "title_es" => "Integrar el Arte Contemporáneo",
                "title_it" => 'Integrare l\'Arte Contemporanea',
                "content_fr" =>
                    "L'art contemporain transforme un simple logement en espace de vie vibrant et personnalisé. Bien intégré, il crée des points focaux puissants et révèle la personnalité des habitants.\n\n**Choisir les Bonnes Œuvres**\n\nLe choix d'une œuvre d'art ne se fait pas à la légère. Elle doit résonner émotionnellement avec les occupants tout en s'harmonisant avec l'architecture et les couleurs de l'espace. Privilégiez des pièces qui vous touchent profondément plutôt que celles qui suivent les tendances du moment.\n\n**L'Échelle et les Proportions**\n\nUne erreur courante consiste à choisir des œuvres trop petites pour l'espace. Un grand format peut transformer radicalement un mur et créer un impact visuel fort. Dans un loft ou un espace avec de hauts plafonds, n'hésitez pas à opter pour des pièces monumentales qui dialoguent avec l'architecture.\n\n**L'Éclairage des Œuvres**\n\nUn bon éclairage révèle toute la puissance d'une œuvre. Spots orientables, éclairages sur rail ou lampes d'accrochage permettent de mettre en valeur chaque pièce sans créer de reflets gênants. La température de couleur de la lumière doit être choisie en fonction du type d'œuvre.\n\n**Mixer les Styles et les Périodes**\n\nAssocier art contemporain et mobilier classique crée des contrastes fascinants. Une toile abstraite moderne sur un mur Haussmannien, une sculpture contemporaine près d'une commode Louis XV : ces juxtapositions créent des dialogues riches entre passé et présent.\n\n**La Collection Évolutive**\n\nConcevoir son intérieur comme une galerie évolutive permet de faire vivre l'espace. Changez régulièrement l'accrochage, ajoutez de nouvelles pièces, créez des thématiques saisonnières. Cette flexibilité maintient l'intérêt et permet à votre espace de raconter une histoire en constante évolution.",
                "content_en" =>
                    "Contemporary art transforms a simple dwelling into a vibrant and personalized living space. Well integrated, it creates powerful focal points and reveals the personality of the inhabitants.\n\n**Choosing the Right Works**\n\nChoosing an artwork is not done lightly. It must resonate emotionally with the occupants while harmonizing with the architecture and colors of the space. Favor pieces that deeply touch you rather than those that follow current trends.\n\n**Scale and Proportions**\n\nA common mistake is choosing works that are too small for the space. A large format can radically transform a wall and create a strong visual impact. In a loft or space with high ceilings, don't hesitate to opt for monumental pieces that dialogue with the architecture.\n\n**Lighting the Works**\n\nGood lighting reveals the full power of a work. Adjustable spots, track lighting or hanging lamps allow highlighting each piece without creating annoying reflections. The color temperature of the light must be chosen according to the type of work.\n\n**Mixing Styles and Periods**\n\nCombining contemporary art and classic furniture creates fascinating contrasts. A modern abstract canvas on a Haussmann wall, a contemporary sculpture near a Louis XV chest: these juxtapositions create rich dialogues between past and present.\n\n**The Evolving Collection**\n\nConceiving your interior as an evolving gallery allows the space to live. Regularly change the hanging, add new pieces, create seasonal themes. This flexibility maintains interest and allows your space to tell an ever-evolving story.",
                "content_es" =>
                    "El arte contemporáneo transforma una simple vivienda en un espacio vital vibrante y personalizado. Bien integrado, crea puntos focales poderosos y revela la personalidad de los habitantes.\n\n**Elegir las Obras Correctas**\n\nElegir una obra de arte no se hace a la ligera. Debe resonar emocionalmente con los ocupantes armonizando con la arquitectura y colores del espacio. Favorezca piezas que lo toquen profundamente en lugar de aquellas que siguen las tendencias actuales.\n\n**Escala y Proporciones**\n\nUn error común es elegir obras demasiado pequeñas para el espacio. Un formato grande puede transformar radicalmente una pared y crear un fuerte impacto visual. En un loft o espacio con techos altos, no dude en optar por piezas monumentales que dialoguen con la arquitectura.\n\n**Iluminar las Obras**\n\nUna buena iluminación revela todo el poder de una obra. Focos ajustables, iluminación en riel o lámparas colgantes permiten resaltar cada pieza sin crear reflejos molestos. La temperatura de color de la luz debe elegirse según el tipo de obra.\n\n**Mezclar Estilos y Períodos**\n\nCombinar arte contemporáneo y muebles clásicos crea contrastes fascinantes. Un lienzo abstracto moderno en una pared Haussmann, una escultura contemporánea cerca de una cómoda Luis XV: estas yuxtaposiciones crean diálogos ricos entre pasado y presente.\n\n**La Colección Evolutiva**\n\nConcebir su interior como una galería evolutiva permite que el espacio viva. Cambie regularmente el colgado, agregue nuevas piezas, cree temas estacionales. Esta flexibilidad mantiene el interés y permite que su espacio cuente una historia en constante evolución.",
                "content_it" =>
                    'L\'arte contemporanea trasforma una semplice abitazione in uno spazio vitale vibrante e personalizzato. Ben integrata, crea punti focali potenti e rivela la personalità degli abitanti.\n\n**Scegliere le Opere Giuste**\n\nLa scelta di un\'opera d\'arte non si fa alla leggera. Deve risuonare emotivamente con gli occupanti armonizzandosi con l\'architettura e i colori dello spazio. Privilegiate pezzi che vi toccano profondamente piuttosto che quelli che seguono le tendenze del momento.\n\n**Scala e Proporzioni**\n\nUn errore comune consiste nello scegliere opere troppo piccole per lo spazio. Un grande formato può trasformare radicalmente una parete e creare un forte impatto visivo. In un loft o spazio con soffitti alti, non esitate a optare per pezzi monumentali che dialogano con l\'architettura.\n\n**Illuminare le Opere**\n\nUna buona illuminazione rivela tutto il potere di un\'opera. Faretti orientabili, illuminazione su binario o lampade da sospensione permettono di valorizzare ogni pezzo senza creare riflessi fastidiosi. La temperatura di colore della luce deve essere scelta in funzione del tipo di opera.\n\n**Mescolare Stili e Periodi**\n\nAssociare arte contemporanea e mobili classici crea contrasti affascinanti. Una tela astratta moderna su un muro Haussmanniano, una scultura contemporanea vicino a una cassettiera Luigi XV: queste giustapposizioni creano dialoghi ricchi tra passato e presente.\n\n**La Collezione Evolutiva**\n\nConcepire il proprio interno come una galleria evolutiva permette allo spazio di vivere. Cambiate regolarmente l\'appendimento, aggiungete nuovi pezzi, create tematiche stagionali. Questa flessibilità mantiene l\'interesse e permette al vostro spazio di raccontare una storia in costante evoluzione.',
                "image" => "medias/images/projects/project-5.jpg",
                "is_published" => true,
                "published_at" => now()->subDays(45),
            ],
            [
                "slug" => "eclairage-architectural",
                "title_fr" => 'L\'Éclairage Architectural',
                "title_en" => "Architectural Lighting",
                "title_es" => "Iluminación Arquitectónica",
                "title_it" => "Illuminazione Architettonica",
                "content_fr" =>
                    "L'éclairage est l'élément invisible qui révèle l'architecture et crée les ambiances. Un projet d'éclairage réussi transforme radicalement la perception d'un espace.\n\n**Les Différents Types d'Éclairage**\n\nL'éclairage général assure la fonctionnalité de l'espace. L'éclairage d'accentuation met en valeur des éléments spécifiques : œuvres d'art, textures murales, objets décoratifs. L'éclairage d'ambiance crée l'atmosphère et le confort visuel. Un bon projet combine ces trois types en couches superposées.\n\n**La Température de Couleur**\n\nLe choix entre lumière chaude (2700-3000K) et lumière froide (4000-5000K) influence considérablement l'atmosphère. Les espaces de vie privilégient les températures chaudes pour leur aspect cocooning, tandis que les zones de travail bénéficient de lumières plus froides pour la concentration.\n\n**L'Éclairage Intégré**\n\nLes systèmes d'éclairage intégrés à l'architecture créent des effets spectaculaires : plafonds lumineux, plinthes LED, niches rétroéclairées. Ces installations discrètes soulignent les volumes et créent une lumière douce et enveloppante.\n\n**La Variation et les Scénarios**\n\nLes variateurs permettent d'adapter l'intensité lumineuse au moment de la journée et à l'usage. Créez des scénarios préprogrammés : lecture, détente, réception, cinéma. La domotique offre aujourd'hui des possibilités infinies de personnalisation.\n\n**L'Éclairage Naturel**\n\nMaximiser la lumière naturelle reste une priorité. Orientation des espaces, choix des revêtements réfléchissants, positionnement stratégique des miroirs : tout doit être pensé pour capter et diffuser la lumière du jour, source de bien-être et d'économies d'énergie.",
                "content_en" =>
                    "Lighting is the invisible element that reveals architecture and creates atmospheres. A successful lighting project radically transforms the perception of a space.\n\n**Different Types of Lighting**\n\nGeneral lighting ensures the functionality of the space. Accent lighting highlights specific elements: artworks, wall textures, decorative objects. Ambient lighting creates atmosphere and visual comfort. A good project combines these three types in superimposed layers.\n\n**Color Temperature**\n\nThe choice between warm light (2700-3000K) and cold light (4000-5000K) considerably influences the atmosphere. Living spaces favor warm temperatures for their cocooning aspect, while work areas benefit from cooler lights for concentration.\n\n**Integrated Lighting**\n\nLighting systems integrated into architecture create spectacular effects: luminous ceilings, LED baseboards, backlit niches. These discreet installations highlight volumes and create soft and enveloping light.\n\n**Variation and Scenarios**\n\nDimmers allow adjusting light intensity to the time of day and use. Create preprogrammed scenarios: reading, relaxation, reception, cinema. Home automation today offers infinite possibilities for customization.\n\n**Natural Lighting**\n\nMaximizing natural light remains a priority. Space orientation, choice of reflective coatings, strategic positioning of mirrors: everything must be thought out to capture and diffuse daylight, source of well-being and energy savings.",
                "content_es" =>
                    "La iluminación es el elemento invisible que revela la arquitectura y crea atmósferas. Un proyecto de iluminación exitoso transforma radicalmente la percepción de un espacio.\n\n**Diferentes Tipos de Iluminación**\n\nLa iluminación general asegura la funcionalidad del espacio. La iluminación de acento resalta elementos específicos: obras de arte, texturas murales, objetos decorativos. La iluminación ambiental crea atmósfera y confort visual. Un buen proyecto combina estos tres tipos en capas superpuestas.\n\n**Temperatura de Color**\n\nLa elección entre luz cálida (2700-3000K) y luz fría (4000-5000K) influye considerablemente en la atmósfera. Los espacios vitales favorecen temperaturas cálidas por su aspecto acogedor, mientras que las zonas de trabajo benefician de luces más frías para la concentración.\n\n**Iluminación Integrada**\n\nLos sistemas de iluminación integrados en la arquitectura crean efectos espectaculares: techos luminosos, rodapiés LED, nichos retroiluminados. Estas instalaciones discretas resaltan los volúmenes y crean luz suave y envolvente.\n\n**Variación y Escenarios**\n\nLos reguladores permiten ajustar la intensidad lumínica al momento del día y al uso. Cree escenarios preprogramados: lectura, relajación, recepción, cine. La domótica ofrece hoy posibilidades infinitas de personalización.\n\n**Iluminación Natural**\n\nMaximizar la luz natural sigue siendo una prioridad. Orientación de espacios, elección de revestimientos reflectantes, posicionamiento estratégico de espejos: todo debe pensarse para captar y difundir la luz del día, fuente de bienestar y ahorro energético.",
                "content_it" =>
                    'L\'illuminazione è l\'elemento invisibile che rivela l\'architettura e crea atmosfere. Un progetto di illuminazione riuscito trasforma radicalmente la percezione di uno spazio.\n\n**Diversi Tipi di Illuminazione**\n\nL\'illuminazione generale assicura la funzionalità dello spazio. L\'illuminazione d\'accento valorizza elementi specifici: opere d\'arte, texture murali, oggetti decorativi. L\'illuminazione ambientale crea atmosfera e comfort visivo. Un buon progetto combina questi tre tipi in strati sovrapposti.\n\n**Temperatura di Colore**\n\nLa scelta tra luce calda (2700-3000K) e luce fredda (4000-5000K) influenza considerevolmente l\'atmosfera. Gli spazi abitativi privilegiano temperature calde per il loro aspetto accogliente, mentre le zone di lavoro beneficiano di luci più fredde per la concentrazione.\n\n**Illuminazione Integrata**\n\nI sistemi di illuminazione integrati nell\'architettura creano effetti spettacolari: soffitti luminosi, battiscopa LED, nicchie retroilluminate. Queste installazioni discrete sottolineano i volumi e creano luce soffusa e avvolgente.\n\n**Variazione e Scenari**\n\nI dimmer permettono di adattare l\'intensità luminosa al momento della giornata e all\'uso. Create scenari preprogrammati: lettura, relax, ricevimento, cinema. La domotica offre oggi possibilità infinite di personalizzazione.\n\n**Illuminazione Naturale**\n\nMassimizzare la luce naturale rimane una priorità. Orientamento degli spazi, scelta di rivestimenti riflettenti, posizionamento strategico di specchi: tutto deve essere pensato per catturare e diffondere la luce del giorno, fonte di benessere e risparmio energetico.',
                "image" => "medias/images/projects/project-6.jpg",
                "is_published" => true,
                "published_at" => now()->subDays(60),
            ],
            [
                "slug" => "textures-tactiles",
                "title_fr" => "Jouer avec les Textures",
                "title_en" => "Playing with Textures",
                "title_es" => "Jugar con las Texturas",
                "title_it" => "Giocare con le Texture",
                "content_fr" =>
                    "Les textures apportent profondeur, richesse et caractère à un intérieur. Leur association crée une expérience sensorielle qui va au-delà du visuel.\n\n**La Règle des Contrastes**\n\nAssocier des textures opposées crée de l'intérêt : velours lisse et lin froissé, marbre poli et bois brut, métal brossé et laine bouclée. Ces contrastes tactiles invitent au toucher et enrichissent l'expérience de l'espace.\n\n**Les Textiles Superposés**\n\nCoussins de différentes matières, plaids en laine mohair, rideaux en lin lourd : superposer les textiles crée une impression de confort et de luxe. Variez les tissages, les épaisseurs et les finitions pour un résultat harmonieux.\n\n**Les Revêtements Muraux**\n\nAu-delà de la peinture, explorez les enduits à la chaux, les papiers peints texturés, les panneaux boisés ou les carreaux en relief. Un mur texturé devient un point focal qui capte la lumière de manière unique.\n\n**Les Matériaux Naturels**\n\nRotin, jonc de mer, terre cuite, pierre brute : ces matériaux apportent des textures organiques qui réchauffent instantanément l'atmosphère. Leur aspect imparfait et leurs variations naturelles créent de l'authenticité.\n\n**L'Équilibre Visuel**\n\nTrop de textures différentes créent de la confusion. Limitez-vous à 3-4 textures dominantes par espace, en les répartissant équitablement. L'œil doit pouvoir voyager naturellement d'une texture à l'autre sans être submergé.",
                "content_en" =>
                    "Textures bring depth, richness and character to an interior. Their association creates a sensory experience that goes beyond the visual.\n\n**The Rule of Contrasts**\n\nCombining opposite textures creates interest: smooth velvet and wrinkled linen, polished marble and raw wood, brushed metal and curly wool. These tactile contrasts invite touch and enrich the experience of the space.\n\n**Layered Textiles**\n\nCushions of different materials, mohair wool throws, heavy linen curtains: layering textiles creates an impression of comfort and luxury. Vary weaves, thicknesses and finishes for a harmonious result.\n\n**Wall Coverings**\n\nBeyond paint, explore lime plasters, textured wallpapers, wood panels or relief tiles. A textured wall becomes a focal point that captures light in a unique way.\n\n**Natural Materials**\n\nRattan, seagrass, terracotta, raw stone: these materials bring organic textures that instantly warm the atmosphere. Their imperfect appearance and natural variations create authenticity.\n\n**Visual Balance**\n\nToo many different textures create confusion. Limit yourself to 3-4 dominant textures per space, distributing them evenly. The eye must be able to travel naturally from one texture to another without being overwhelmed.",
                "content_es" =>
                    "Las texturas aportan profundidad, riqueza y carácter a un interior. Su asociación crea una experiencia sensorial que va más allá de lo visual.\n\n**La Regla de los Contrastes**\n\nCombinar texturas opuestas crea interés: terciopelo liso y lino arrugado, mármol pulido y madera cruda, metal cepillado y lana rizada. Estos contrastes táctiles invitan al tacto y enriquecen la experiencia del espacio.\n\n**Textiles Superpuestos**\n\nCojines de diferentes materiales, mantas de lana mohair, cortinas de lino pesado: superponer textiles crea una impresión de confort y lujo. Varíe los tejidos, espesores y acabados para un resultado armonioso.\n\n**Revestimientos Murales**\n\nMás allá de la pintura, explore enlucidos de cal, papeles pintados texturizados, paneles de madera o azulejos en relieve. Una pared texturizada se convierte en un punto focal que captura la luz de manera única.\n\n**Materiales Naturales**\n\nRatán, junco de mar, terracota, piedra bruta: estos materiales aportan texturas orgánicas que calientan instantáneamente la atmósfera. Su aspecto imperfecto y variaciones naturales crean autenticidad.\n\n**Equilibrio Visual**\n\nDemasiadas texturas diferentes crean confusión. Limítese a 3-4 texturas dominantes por espacio, distribuyéndolas equitativamente. El ojo debe poder viajar naturalmente de una textura a otra sin sentirse abrumado.",
                "content_it" =>
                    'Le texture portano profondità, ricchezza e carattere a un interno. La loro associazione crea un\'esperienza sensoriale che va oltre il visivo.\n\n**La Regola dei Contrasti**\n\nCombinare texture opposte crea interesse: velluto liscio e lino stropicciato, marmo lucido e legno grezzo, metallo spazzolato e lana riccia. Questi contrasti tattili invitano al tocco e arricchiscono l\'esperienza dello spazio.\n\n**Tessuti Sovrapposti**\n\nCuscini di diverse materie, plaid in lana mohair, tende in lino pesante: sovrapporre i tessuti crea un\'impressione di comfort e lusso. Variate le tessiture, gli spessori e le finiture per un risultato armonioso.\n\n**Rivestimenti Murali**\n\nOltre la pittura, esplorate intonaci a calce, carte da parati texturizzate, pannelli in legno o piastrelle in rilievo. Una parete texturizzata diventa un punto focale che cattura la luce in modo unico.\n\n**Materiali Naturali**\n\nRattan, giunco di mare, terracotta, pietra grezza: questi materiali portano texture organiche che scaldano istantaneamente l\'atmosfera. Il loro aspetto imperfetto e le variazioni naturali creano autenticità.\n\n**Equilibrio Visivo**\n\nTroppe texture diverse creano confusione. Limitatevi a 3-4 texture dominanti per spazio, distribuendole equamente. L\'occhio deve poter viaggiare naturalmente da una texture all\'altra senza essere sopraffatto.',
                "image" => "medias/images/projects/project-7.jpg",
                "is_published" => false,
                "published_at" => null,
            ],
            [
                "slug" => "cuisine-ouverte-moderne",
                "title_fr" => "La Cuisine Ouverte Moderne",
                "title_en" => "The Modern Open Kitchen",
                "title_es" => "La Cocina Abierta Moderna",
                "title_it" => "La Cucina Aperta Moderna",
                "content_fr" =>
                    'La cuisine ouverte est devenue le cœur de la maison, un espace de convivialité où se mêlent préparation culinaire et vie sociale.\n\n**Délimiter sans Cloisonner**\n\nBien que ouverte, la cuisine nécessite une définition visuelle. Îlot central, différence de revêtements de sol, changement de niveau de plafond ou suspension design permettent de créer une séparation subtile sans perdre la fluidité spatiale.\n\n**L\'Îlot Multifonction**\n\nL\'îlot central devient le point névralgique : espace de cuisson, plan de travail, bar pour les repas rapides et lieu de socialisation. Équipé de rangements astucieux, il optimise l\'espace tout en créant une circulation naturelle.\n\n**La Gestion des Odeurs et du Bruit**\n\nUne hotte performante et silencieuse est indispensable. Privilégiez les modèles avec fort débit d\'extraction et niveau sonore réduit. Les matériaux absorbants (bois, tissus) dans le salon adjacent atténuent la réverbération.\n\n**L\'Harmonie Esthétique**\n\nLa cuisine ouverte doit dialoguer harmonieusement avec l\'espace de vie. Coordonnez les matériaux, les couleurs et le style. Une cuisine minimaliste aux lignes épurées s\'intégrera parfaitement dans un salon contemporain.\n\n**Le Rangement Optimisé**\n\nDans une cuisine ouverte, l\'ordre est crucial. Prévoyez des rangements généreux et des solutions dissimulées : garde-manger coulissant, électroménagers encastrés, tiroirs profonds. Tout doit pouvoir disparaître pour maintenir une esthétique épurée.',
                "content_en" =>
                    'The open kitchen has become the heart of the home, a space of conviviality where culinary preparation and social life mix.\n\n**Delimiting without Partitioning**\n\nAlthough open, the kitchen requires visual definition. Central island, difference in floor coverings, change in ceiling level or design suspension allow creating a subtle separation without losing spatial fluidity.\n\n**The Multifunctional Island**\n\nThe central island becomes the nerve center: cooking space, work surface, bar for quick meals and socializing place. Equipped with clever storage, it optimizes space while creating natural circulation.\n\n**Managing Odors and Noise**\n\nA high-performance and silent hood is essential. Favor models with strong extraction flow and reduced noise level. Absorbent materials (wood, fabrics) in the adjacent living room attenuate reverberation.\n\n**Aesthetic Harmony**\n\nThe open kitchen must dialogue harmoniously with the living space. Coordinate materials, colors and style. A minimalist kitchen with clean lines will integrate perfectly into a contemporary living room.\n\n**Optimized Storage**\n\nIn an open kitchen, order is crucial. Provide generous storage and concealed solutions: sliding pantry, built-in appliances, deep drawers. Everything must be able to disappear to maintain a refined aesthetic.',
                "content_es" =>
                    'La cocina abierta se ha convertido en el corazón del hogar, un espacio de convivencia donde se mezclan la preparación culinaria y la vida social.\n\n**Delimitar sin Tabiques**\n\nAunque abierta, la cocina requiere definición visual. Isla central, diferencia en revestimientos de suelo, cambio de nivel de techo o suspensión de diseño permiten crear una separación sutil sin perder la fluidez espacial.\n\n**La Isla Multifunción**\n\nLa isla central se convierte en el centro neurálgico: espacio de cocción, superficie de trabajo, barra para comidas rápidas y lugar de socialización. Equipada con almacenamiento inteligente, optimiza el espacio creando circulación natural.\n\n**Gestión de Olores y Ruido**\n\nUna campana de alto rendimiento y silenciosa es esencial. Favorezca modelos con fuerte flujo de extracción y nivel de ruido reducido. Los materiales absorbentes (madera, telas) en la sala de estar adyacente atenúan la reverberación.\n\n**Armonía Estética**\n\nLa cocina abierta debe dialogar armoniosamente con el espacio vital. Coordine materiales, colores y estilo. Una cocina minimalista con líneas limpias se integrará perfectamente en una sala de estar contemporánea.\n\n**Almacenamiento Optimizado**\n\nEn una cocina abierta, el orden es crucial. Prevea almacenamiento generoso y soluciones ocultas: despensa deslizante, electrodomésticos empotrados, cajones profundos. Todo debe poder desaparecer para mantener una estética refinada.',
                "content_it" =>
                    'La cucina aperta è diventata il cuore della casa, uno spazio di convivialità dove si mescolano preparazione culinaria e vita sociale.\n\n**Delimitare senza Partizionare**\n\nSebbene aperta, la cucina necessita di una definizione visiva. Isola centrale, differenza di rivestimenti del pavimento, cambio di livello del soffitto o sospensione design permettono di creare una separazione sottile senza perdere la fluidità spaziale.\n\n**L\'Isola Multifunzione**\n\nL\'isola centrale diventa il punto nevralgico: spazio di cottura, piano di lavoro, bar per pasti veloci e luogo di socializzazione. Equipaggiata con ripostigli intelligenti, ottimizza lo spazio creando circolazione naturale.\n\n**La Gestione degli Odori e del Rumore**\n\nUna cappa performante e silenziosa è indispensabile. Privilegiate modelli con forte flusso di estrazione e livello sonoro ridotto. I materiali assorbenti (legno, tessuti) nel soggiorno adiacente attenuano il riverbero.\n\n**L\'Armonia Estetica**\n\nLa cucina aperta deve dialogare armoniosamente con lo spazio vitale. Coordinate materiali, colori e stile. Una cucina minimalista dalle linee pulite si integrerà perfettamente in un soggiorno contemporaneo.\n\n**Il Ripostiglio Ottimizzato**\n\nIn una cucina aperta, l\'ordine è cruciale. Prevedete ripostigli generosi e soluzioni dissimulate: dispensa scorrevole, elettrodomestici incassati, cassetti profondi. Tutto deve poter scomparire per mantenere un\'estetica raffinata.',
                "image" => "medias/images/projects/project-8.jpg",
                "is_published" => false,
                "published_at" => null,
            ],
            [
                "slug" => "salle-bain-spa",
                "title_fr" => "Créer une Salle de Bain Spa",
                "title_en" => "Creating a Spa Bathroom",
                "title_es" => "Crear un Baño Spa",
                "title_it" => "Creare un Bagno Spa",
                "content_fr" =>
                    "Transformer sa salle de bain en sanctuaire de bien-être est un investissement dans son quotidien. Quelques aménagements stratégiques suffisent à créer une ambiance spa luxueuse.\n\n**Les Matériaux Zen**\n\nPrivilégiez les matériaux naturels : pierre naturelle, bois exotique imputrescible, galets, bambou. Ces matériaux créent une connexion apaisante avec la nature. Le teck pour le sol de douche, le marbre pour les vasques, le travertin pour les murs : chaque surface contribue à l'atmosphère.\n\n**La Douche Pluie**\n\nUne large pomme de douche effet pluie transforme la douche quotidienne en rituel ressourçant. Ajoutez des jets latéraux, une colonne de douche thermostatique et un banc en teck pour une expérience complète. La douche à l'italienne de plain-pied renforce l'impression d'espace.\n\n**L'Éclairage Tamisé**\n\nÉvitez l'éclairage direct agressif. Privilégiez l'éclairage indirect : LED derrière le miroir, spots encastrés dimmables, bougies LED réalistes. Un variateur permet d'adapter l'ambiance du réveil dynamique à la détente vespérale.\n\n**Le Confort Thermique**\n\nSèche-serviettes design, sol chauffant et température ambiante contrôlée créent un cocon douillet. Sortir de la douche dans une salle de bain à 24°C avec une serviette préchauffée : c'est l'expérience spa à domicile.\n\n**Les Rangements Invisibles**\n\nTout doit disparaître pour maintenir la sérénité visuelle. Niches murales carrelées, meubles suspendus avec tiroirs profonds, miroirs avec rangements intégrés : l'ordre est la clé d'un espace zen.",
                "content_en" =>
                    "Transforming your bathroom into a wellness sanctuary is an investment in your daily life. A few strategic arrangements are enough to create a luxurious spa ambiance.\n\n**Zen Materials**\n\nFavor natural materials: natural stone, rot-proof exotic wood, pebbles, bamboo. These materials create a soothing connection with nature. Teak for shower floor, marble for sinks, travertine for walls: each surface contributes to the atmosphere.\n\n**Rain Shower**\n\nA large rain effect shower head transforms the daily shower into a restorative ritual. Add side jets, a thermostatic shower column and a teak bench for a complete experience. The walk-in Italian shower reinforces the impression of space.\n\n**Subdued Lighting**\n\nAvoid aggressive direct lighting. Favor indirect lighting: LED behind mirror, dimmable recessed spots, realistic LED candles. A dimmer allows adapting the ambiance from dynamic wake-up to evening relaxation.\n\n**Thermal Comfort**\n\nDesign towel warmer, heated floor and controlled ambient temperature create a cozy cocoon. Getting out of the shower in a bathroom at 24°C with a preheated towel: that's the home spa experience.\n\n**Invisible Storage**\n\nEverything must disappear to maintain visual serenity. Tiled wall niches, suspended furniture with deep drawers, mirrors with integrated storage: order is the key to a zen space.",
                "content_es" =>
                    "Transformar su baño en un santuario de bienestar es una inversión en su vida diaria. Algunos arreglos estratégicos son suficientes para crear un ambiente de spa lujoso.\n\n**Materiales Zen**\n\nFavorezca materiales naturales: piedra natural, madera exótica imputrescible, guijarros, bambú. Estos materiales crean una conexión relajante con la naturaleza. Teca para el suelo de ducha, mármol para lavabos, travertino para paredes: cada superficie contribuye a la atmósfera.\n\n**Ducha de Lluvia**\n\nUn cabezal de ducha grande con efecto lluvia transforma la ducha diaria en un ritual restaurador. Agregue jets laterales, una columna de ducha termostática y un banco de teca para una experiencia completa. La ducha italiana a ras de suelo refuerza la impresión de espacio.\n\n**Iluminación Tenue**\n\nEvite la iluminación directa agresiva. Favorezca iluminación indirecta: LED detrás del espejo, focos empotrados regulables, velas LED realistas. Un regulador permite adaptar el ambiente desde el despertar dinámico hasta la relajación vespertina.\n\n**Confort Térmico**\n\nToallero de diseño, suelo radiante y temperatura ambiente controlada crean un capullo acogedor. Salir de la ducha en un baño a 24°C con una toalla precalentada: esa es la experiencia de spa en casa.\n\n**Almacenamiento Invisible**\n\nTodo debe desaparecer para mantener la serenidad visual. Nichos murales alicatados, muebles suspendidos con cajones profundos, espejos con almacenamiento integrado: el orden es la clave de un espacio zen.",
                "content_it" =>
                    'Trasformare il proprio bagno in un santuario del benessere è un investimento nella propria vita quotidiana. Alcuni arrangiamenti strategici sono sufficienti per creare un\'atmosfera spa lussuosa.\n\n**Materiali Zen**\n\nPrivilegiate materiali naturali: pietra naturale, legno esotico imputrescibile, ciottoli, bambù. Questi materiali creano una connessione rilassante con la natura. Teak per il pavimento della doccia, marmo per i lavabi, travertino per le pareti: ogni superficie contribuisce all\'atmosfera.\n\n**Doccia a Pioggia**\n\nUn grande soffione effetto pioggia trasforma la doccia quotidiana in un rituale rigenerante. Aggiungete getti laterali, una colonna doccia termostatica e una panca in teak per un\'esperienza completa. La doccia italiana a filo pavimento rafforza l\'impressione di spazio.\n\n**Illuminazione Soffusa**\n\nEvitate l\'illuminazione diretta aggressiva. Privilegiate l\'illuminazione indiretta: LED dietro lo specchio, faretti incassati dimmerabili, candele LED realistiche. Un dimmer permette di adattare l\'atmosfera dal risveglio dinamico al relax serale.\n\n**Comfort Termico**\n\nScaldabagno design, pavimento riscaldato e temperatura ambiente controllata creano un bozzolo accogliente. Uscire dalla doccia in un bagno a 24°C con un asciugamano preriscaldato: questa è l\'esperienza spa a casa.\n\n**Ripostigli Invisibili**\n\nTutto deve scomparire per mantenere la serenità visiva. Nicchie murali piastrellate, mobili sospesi con cassetti profondi, specchi con ripostigli integrati: l\'ordine è la chiave di uno spazio zen.',
                "image" => "medias/images/projects/project-9.jpg",
                "is_published" => true,
                "published_at" => now()->subDays(75),
            ],
            [
                "slug" => "bureau-maison-productif",
                "title_fr" => "Le Bureau à Domicile Idéal",
                "title_en" => "The Ideal Home Office",
                "title_es" => "La Oficina en Casa Ideal",
                "title_it" => 'L\'Ufficio a Casa Ideale',
                "content_fr" =>
                    "Avec la généralisation du télétravail, créer un espace de travail fonctionnel et inspirant chez soi n'est plus un luxe mais une nécessité.\n\n**L'Emplacement Stratégique**\n\nIdéalement, le bureau doit être dans un espace dédié avec porte, loin des zones de passage. Si l'espace manque, une alcôve aménagée, un coin de chambre ou un placard transformé peuvent faire l'affaire. L'important est de créer une séparation physique ou visuelle entre travail et vie personnelle.\n\n**L'Ergonomie Avant Tout**\n\nInvestissez dans un fauteuil ergonomique de qualité : c'est votre outil de travail principal. Le bureau doit être à la bonne hauteur (coudes à 90°), l'écran à hauteur des yeux. Un support d'ordinateur portable, un clavier et une souris externes transforment le confort de travail.\n\n**La Lumière Naturelle**\n\nPositionnez le bureau perpendiculairement à la fenêtre pour éviter les reflets sur l'écran tout en bénéficiant de lumière naturelle. Un éclairage d'appoint direct (lampe de bureau LED) et un éclairage ambiant complètent l'installation.\n\n**L'Acoustique**\n\nLes visioconférences nécessitent un environnement calme. Rideaux épais, tapis, panneaux acoustiques design et bibliothèque remplie absorbent les sons et améliorent la qualité audio.\n\n**La Personnalisation Inspirante**\n\nVotre bureau doit refléter votre personnalité et vous inspirer. Œuvres d'art, plantes, objets de collection ou photos : créez un environnement qui stimule votre créativité. Un espace ordonné avec des rangements astucieux favorise la concentration.",
                "content_en" =>
                    "With the generalization of remote work, creating a functional and inspiring workspace at home is no longer a luxury but a necessity.\n\n**Strategic Location**\n\nIdeally, the office should be in a dedicated space with door, away from traffic areas. If space is lacking, a fitted alcove, a corner of bedroom or a transformed closet can do. The important thing is to create a physical or visual separation between work and personal life.\n\n**Ergonomics First**\n\nInvest in a quality ergonomic chair: it's your main work tool. The desk must be at the right height (elbows at 90°), the screen at eye level. A laptop stand, an external keyboard and mouse transform work comfort.\n\n**Natural Light**\n\nPosition the desk perpendicular to the window to avoid screen reflections while benefiting from natural light. Direct supplementary lighting (LED desk lamp) and ambient lighting complete the installation.\n\n**Acoustics**\n\nVideo conferences require a quiet environment. Thick curtains, carpet, design acoustic panels and filled bookcase absorb sounds and improve audio quality.\n\n**Inspiring Personalization**\n\nYour office must reflect your personality and inspire you. Artworks, plants, collectibles or photos: create an environment that stimulates your creativity. An orderly space with clever storage promotes concentration.",
                "content_es" =>
                    "Con la generalización del trabajo remoto, crear un espacio de trabajo funcional e inspirador en casa ya no es un lujo sino una necesidad.\n\n**Ubicación Estratégica**\n\nIdealmente, la oficina debe estar en un espacio dedicado con puerta, lejos de zonas de paso. Si falta espacio, una alcoba acondicionada, un rincón de dormitorio o un armario transformado pueden funcionar. Lo importante es crear una separación física o visual entre trabajo y vida personal.\n\n**Ergonomía Ante Todo**\n\nInvierta en una silla ergonómica de calidad: es su herramienta de trabajo principal. El escritorio debe estar a la altura correcta (codos a 90°), la pantalla a la altura de los ojos. Un soporte para portátil, un teclado y ratón externos transforman el confort de trabajo.\n\n**Luz Natural**\n\nPosicione el escritorio perpendicular a la ventana para evitar reflejos en la pantalla beneficiándose de luz natural. Iluminación suplementaria directa (lámpara de escritorio LED) e iluminación ambiental completan la instalación.\n\n**Acústica**\n\nLas videoconferencias requieren un ambiente tranquilo. Cortinas gruesas, alfombra, paneles acústicos de diseño y estantería llena absorben sonidos y mejoran la calidad de audio.\n\n**Personalización Inspiradora**\n\nSu oficina debe reflejar su personalidad e inspirarle. Obras de arte, plantas, objetos de colección o fotos: cree un ambiente que estimule su creatividad. Un espacio ordenado con almacenamiento inteligente favorece la concentración.",
                "content_it" =>
                    'Con la generalizzazione del lavoro da remoto, creare uno spazio di lavoro funzionale e ispirante a casa non è più un lusso ma una necessità.\n\n**Posizione Strategica**\n\nIdealmente, l\'ufficio dovrebbe essere in uno spazio dedicato con porta, lontano dalle zone di passaggio. Se lo spazio manca, un\'alcova attrezzata, un angolo di camera da letto o un armadio trasformato possono andare bene. L\'importante è creare una separazione fisica o visiva tra lavoro e vita personale.\n\n**Ergonomia Prima di Tutto**\n\nInvestite in una sedia ergonomica di qualità: è il vostro strumento di lavoro principale. La scrivania deve essere all\'altezza giusta (gomiti a 90°), lo schermo all\'altezza degli occhi. Un supporto per laptop, una tastiera e un mouse esterni trasformano il comfort di lavoro.\n\n**Luce Naturale**\n\nPosizionate la scrivania perpendicolare alla finestra per evitare riflessi sullo schermo beneficiando di luce naturale. Un\'illuminazione supplementare diretta (lampada da scrivania LED) e un\'illuminazione ambientale completano l\'installazione.\n\n**Acustica**\n\nLe videoconferenze richiedono un ambiente tranquillo. Tende spesse, tappeto, pannelli acustici design e libreria piena assorbono i suoni e migliorano la qualità audio.\n\n**Personalizzazione Ispirant**\n\nIl vostro ufficio deve riflettere la vostra personalità e ispirarvi. Opere d\'arte, piante, oggetti da collezione o foto: create un ambiente che stimoli la vostra creatività. Uno spazio ordinato con ripostigli intelligenti favorisce la concentrazione.',
                "image" => "medias/images/projects/project-10.jpg",
                "is_published" => true,
                "published_at" => now()->subDays(90),
            ],
        ];

        foreach ($blogs as $blog) {
            Blog::create($blog);
        }

        $this->command->info(
            "✅ " . count($blogs) . " blogs créés avec succès !",
        );
    }
}
